owner: the1ev234 # Your GitHub organization or username, where this repository lives
repo: thermal-status # The name of this repository
user-agent: the1ev234

sites:
  - name: Thermal
    url: https://thermaz.online
    logoUrl: https://raw.githubusercontent.com/tp-link-extender/status/main/Mercury.svg
  - name: Client setup
    url: https://setup.thermaz.online
    logoUrl: https://raw.githubusercontent.com/tp-link-extender/status/main/Mercury.svg
  - name: Orbiter
    url: https://gs.thermaz.online
    logoUrl: https://raw.githubusercontent.com/tp-link-extender/status/main/Mercury.svg
    expectedStatusCodes:
      - 404

assignees:
  - the1ev234

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.thermaz.online
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/tp-link-extender/status/main/Mercury.svg
  name: Thermal
  introTitle: "Thermal status"
  navbar:
    - title: thermal
      href: https://thermaz.online
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/the1ev234/thermal-status

i18n:
  footer: "[Mercury](https://mercs.dev). This page is [open source]($REPO)."

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
